name: ditst
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Serial port terminal
description: |
   Dinawari is a packet lossless and dark themed serialport terminal.
   It supports file and hex sneding.

#grade: stable # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  ditst:
    command: qt5-launch Dinawari
    plugs: [home, serial-port, x11]

parts:
  ditst:
    plugin: qmake
    qt-version: qt5
    source-type: git
    source: https://github.com/growingkid/Dinawari.git
    build-packages:
      - qtbase5-dev
    stage-packages:
      - libqt5gui5
